// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIQIl4PQTJf4gdntgPyMOiyhJqr7TcLFY',
    appId: '1:30900045260:android:71c0671713d8670735c969',
    messagingSenderId: '30900045260',
    projectId: 'fast-feast-cb407',
    databaseURL: 'https://fast-feast-cb407-default-rtdb.firebaseio.com',
    storageBucket: 'fast-feast-cb407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtuWeP1-nlwwQeJQJN5hOtDDoQy-aUbFU',
    appId: '1:30900045260:ios:122186a538b7781235c969',
    messagingSenderId: '30900045260',
    projectId: 'fast-feast-cb407',
    databaseURL: 'https://fast-feast-cb407-default-rtdb.firebaseio.com',
    storageBucket: 'fast-feast-cb407.firebasestorage.app',
    androidClientId: '30900045260-p2i3kc62jmg1ishbmhi4kvnqh921tdfm.apps.googleusercontent.com',
    iosClientId: '30900045260-naii79a6p2gs9j7bcs9m11f4uoevt0en.apps.googleusercontent.com',
    iosBundleId: 'com.jahid.fastfeast',
  );
}
